package api.inventory;

public enum InventoryType {
    PLAYER_INVENTORY,
    PLAYER_INVENTORY_REFINERY,
    PLAYER_INVENTORY_FACTORY,
    CREATIVE,
    CREATIVE_SHIPYARD,
    STORAGE_BOX,
    FACTORY,
    SHIPYARD
}
